const KOST_WISHLIST_KEY="aup-saved-properties-v1";
const kostMeta={slug:"ubud-green-kost",title:"Ubud Green Kost",location:"Ubud",type:"Kost",purpose:"rent",usd:230,idr:3600000,priceSuffix:"month",beds:1,baths:1,area:"24 m²",image:"https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1400&q=88"};
let kostLang=localStorage.getItem("aup-language")||"en";
let kostCurrency=localStorage.getItem("aup-currency")||"USD";

(function ensureWishlistStyles(){if(document.querySelector('link[href="../wishlist.css"]'))return;const l=document.createElement("link");l.rel="stylesheet";l.href="../wishlist.css";document.head.appendChild(l)})();
(function ensureCatalogFeatures(){if(document.querySelector('script[data-catalog-features-loader]'))return;const s=document.createElement("script");s.src="../catalog-features.js";s.dataset.catalogFeaturesLoader="true";s.async=false;document.head.appendChild(s)})();

function readKostSaved(){try{const parsed=JSON.parse(localStorage.getItem(KOST_WISHLIST_KEY)||"[]");return Array.isArray(parsed)?parsed:[]}catch{return[]}}
function writeKostSaved(items){localStorage.setItem(KOST_WISHLIST_KEY,JSON.stringify(items))}
function kostSaved(){return readKostSaved().some(x=>x.slug===kostMeta.slug)}
function showKostToast(text){const el=document.getElementById("propertyToast");if(!el)return;el.textContent=text;el.classList.add("show");clearTimeout(window.__kostToast);window.__kostToast=setTimeout(()=>el.classList.remove("show"),2500)}
function injectKostSavedNav(){const actions=document.querySelector(".header-actions");if(actions&&!actions.querySelector(".saved-nav-link")){const a=document.createElement("a");a.href="../saved.html";a.className="saved-nav-link";a.innerHTML='<span class="saved-nav-heart">♡</span><span class="saved-nav-label"></span><span class="saved-count">0</span>';actions.insertBefore(a,actions.querySelector("#languageToggle")||actions.firstChild)}const da=document.querySelector(".detail-actions");if(da&&!da.querySelector(".detail-save-btn")){const b=document.createElement("button");b.type="button";b.className="detail-save-btn";b.id="kostSave";b.innerHTML='<span class="save-heart">♡</span><span class="save-label"></span>';b.addEventListener("click",toggleKostSaved);da.appendChild(b)}updateKostSavedUi()}
function updateKostSavedUi(){const saved=kostSaved(),items=readKostSaved();document.querySelectorAll(".saved-count").forEach(el=>el.textContent=items.length);document.querySelectorAll(".saved-nav-label").forEach(el=>el.textContent=kostLang==="id"?"Tersimpan":"Saved");const b=document.getElementById("kostSave");if(b){b.classList.toggle("is-saved",saved);b.setAttribute("aria-pressed",String(saved));b.querySelector(".save-heart").textContent=saved?"♥":"♡";b.querySelector(".save-label").textContent=saved?(kostLang==="id"?"Tersimpan":"Saved"):(kostLang==="id"?"Simpan kamar":"Save room")}}
function toggleKostSaved(){const items=readKostSaved(),i=items.findIndex(x=>x.slug===kostMeta.slug);let added=false;if(i>=0)items.splice(i,1);else{items.push({...kostMeta});added=true}writeKostSaved(items);updateKostSavedUi();showKostToast(kostLang==="id"?(added?"Kamar disimpan ke daftar pilihanmu.":"Kamar dihapus dari daftar pilihanmu."):(added?"Room saved to your shortlist.":"Room removed from your shortlist."))}
function applyKostLanguage(){document.documentElement.lang=kostLang;document.querySelectorAll("[data-en][data-id]").forEach(el=>{el.textContent=el.dataset[kostLang]});const ta=document.querySelector("#inquiryForm textarea");if(ta)ta.placeholder=kostLang==="id"?ta.dataset.placeholderId:ta.dataset.placeholderEn;const l=document.getElementById("languageToggle");if(l)l.textContent=kostLang.toUpperCase();updateKostSavedUi();updateKostPrice()}
function updateKostPrice(){const p=document.getElementById("detailPrice"),s=document.getElementById("detailPriceSuffix"),c=document.getElementById("currencyToggle");if(p)p.textContent=kostCurrency==="USD"?`$${kostMeta.usd.toLocaleString("en-US")}`:`Rp ${kostMeta.idr.toLocaleString("id-ID")}`;if(s)s.textContent=kostLang==="id"?"/ bulan":"/ month";if(c)c.textContent=kostCurrency}

injectKostSavedNav();applyKostLanguage();
document.getElementById("languageToggle")?.addEventListener("click",()=>{kostLang=kostLang==="en"?"id":"en";localStorage.setItem("aup-language",kostLang);applyKostLanguage()});
document.getElementById("currencyToggle")?.addEventListener("click",()=>{kostCurrency=kostCurrency==="USD"?"IDR":"USD";localStorage.setItem("aup-currency",kostCurrency);updateKostPrice()});
document.getElementById("detailInquiry")?.addEventListener("click",()=>document.getElementById("inquiryForm")?.scrollIntoView({behavior:"smooth",block:"center"}));
document.getElementById("paypalInfo")?.addEventListener("click",()=>showKostToast(kostLang==="id"?"Pembayaran versi produksi akan dikonfirmasi manual oleh admin.":"Production payment details will be confirmed manually by admin."));
document.getElementById("inquiryForm")?.addEventListener("submit",e=>{e.preventDefault();showKostToast(kostLang==="id"?"Inquiry demo diterima. tidak ada data yang dikirim.":"Demo inquiry received. no data was sent.");e.currentTarget.reset()});
window.addEventListener("storage",updateKostSavedUi);