import test from 'node:test';import assert from 'node:assert/strict';
globalThis.Deno={serve(){}};
const {handle}=await import('../../supabase/functions/admin-media/index.ts');
const env={url:'https://example.invalid',key:'server-only-test-key'};
const id='00000000-0000-4000-8000-000000000001';
const json=(body,status=200)=>new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json'}});
const req=(body,headers={})=>new Request('https://example.invalid/functions/v1/admin-media',{method:'POST',headers:{Authorization:'Bearer user-test-token','Content-Type':'application/json',...headers},body:JSON.stringify(body)});
test('endpoint rejects missing auth and nonstaff users',async()=>{const old=globalThis.fetch;try{assert.equal((await handle(new Request('https://example.invalid',{method:'POST'}),env)).status,401);globalThis.fetch=async()=>json({id,app_metadata:{},user_metadata:{aup_role:'admin'}});assert.equal((await handle(req({action:'list',table:'properties',id}),env)).status,403);}finally{globalThis.fetch=old;}});
test('endpoint rejects other origins, tables and malformed IDs',async()=>{const old=globalThis.fetch;try{globalThis.fetch=async()=>json({id,app_metadata:{aup_role:'admin'}});assert.equal((await handle(req({}, {Origin:'https://evil.invalid'}),env)).status,403);assert.equal((await handle(req({action:'list',table:'auth.users',id}),env)).status,400);assert.equal((await handle(req({action:'list',table:'properties',id:'../other'}),env)).status,400);}finally{globalThis.fetch=old;}});
test('valid upload verifies user, uses caller RLS and makes private bucket',async()=>{const old=globalThis.fetch,calls=[];try{globalThis.fetch=async(url,init={})=>{calls.push({url,init});if(url.endsWith('/auth/v1/user'))return json({id,app_metadata:{aup_role:'editor'}});if(url.includes('/rest/v1/properties'))return json([{id}]);if(url.endsWith('/storage/v1/bucket/aup-media'))return json({public:false});if(url.includes('/storage/v1/object/aup-media/'))return json({});if(url.includes('/rest/v1/property_images?'))return json([]);if(url.endsWith('/rest/v1/property_images'))return json([{id:'new-image'}]);throw Error(url);};const form=new FormData();form.set('table','properties');form.set('id',id);form.set('file',new File([new Uint8Array([137,80,78,71,13,10,26,10])],'x.png',{type:'image/png'}));const result=await handle(new Request('https://example.invalid',{method:'POST',headers:{Authorization:'Bearer user-test-token'},body:form}),env);assert.equal(result.status,200);const insert=calls.find(c=>c.url.endsWith('/rest/v1/property_images'));assert.equal(insert.init.headers.Authorization,'Bearer user-test-token');assert.equal(JSON.parse(insert.init.body).property_id,id);assert.equal(JSON.parse(insert.init.body).is_cover,true);const upload=calls.find(c=>c.url.includes('/storage/v1/object/aup-media/'));assert.equal(upload.init.headers.Authorization,'Bearer server-only-test-key');}finally{globalThis.fetch=old;}});
test('failed database insertion removes uploaded orphan',async()=>{const old=globalThis.fetch;let cleanup=false;try{globalThis.fetch=async(url,init={})=>{if(url.endsWith('/auth/v1/user'))return json({id,app_metadata:{aup_role:'admin'}});if(url.includes('/rest/v1/properties'))return json([{id}]);if(url.endsWith('/storage/v1/bucket/aup-media'))return json({public:false});if(url.includes('/storage/v1/object/aup-media/'))return json({});if(url.endsWith('/storage/v1/object/aup-media')){cleanup=true;return json({});}if(url.includes('/rest/v1/property_images?'))return json([]);if(url.endsWith('/rest/v1/property_images'))return json({},400);throw Error(url);};const form=new FormData();form.set('table','properties');form.set('id',id);form.set('file',new File([new Uint8Array([255,216,255])],'x.jpg',{type:'image/jpeg'}));assert.equal((await handle(new Request('https://example.invalid',{method:'POST',headers:{Authorization:'Bearer user-test-token'},body:form}),env)).status,500);assert.equal(cleanup,true);}finally{globalThis.fetch=old;}});

test('guest upload inserts a draft without consent and listing signs only caller-authorized record',async()=>{
 const old=globalThis.fetch;let inserted;try{globalThis.fetch=async(url,init={})=>{if(url.endsWith('/auth/v1/user'))return json({id,app_metadata:{aup_role:'editor'}});if(url.endsWith('/storage/v1/bucket/aup-media'))return json({public:false});if(url.includes('/storage/v1/object/aup-media/'))return json({});if(url.endsWith('/rest/v1/guest_moments')){assert.equal(init.headers.Authorization,'Bearer user-test-token');inserted=JSON.parse(init.body);return json([{id,...inserted}]);}throw Error(url);};const form=new FormData();form.set('table','guest_moments');form.set('file',new File([new Uint8Array([255,216,255])],'guest.jpg',{type:'image/jpeg'}));const result=await handle(new Request('https://example.invalid',{method:'POST',headers:{Authorization:'Bearer user-test-token'},body:form}),env);assert.equal(result.status,200);assert.equal(inserted.publication_status,'draft');assert.equal(inserted.consent_confirmed,false);assert.match(inserted.storage_path,/^guest_moments\//);
 globalThis.fetch=async(url,init={})=>{if(url.endsWith('/auth/v1/user'))return json({id,app_metadata:{aup_role:'editor'}});if(url.includes('/rest/v1/guest_moments?')){assert.equal(init.headers.Authorization,'Bearer user-test-token');return json([]);}throw Error('Unauthorized record must not be signed');};assert.equal((await handle(req({action:'list',table:'guest_moments',id}),env)).status,404);
 }finally{globalThis.fetch=old;}
});
