import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {pathToFileURL} from 'node:url';import {resolve} from 'node:path';import {parseHTML} from 'linkedom';
const source=await readFile(new URL('../app.js',import.meta.url),'utf8');let iteration=0;
async function openPanel(role,authenticated=true){
 const {window}=parseHTML('<html><body><main id="app"></main><div id="notice"></div></body></html>');Object.assign(globalThis,{window,document:window.document,sessionStorage:{},confirm:()=>true});
 const user={id:'test',email:'admin@example.invalid',app_metadata:{aup_role:role}};
 const fake={auth:{getSession:async()=>({data:{session:authenticated?{access_token:'fake'}:null}}),getUser:async()=>({data:{user}}),signOut:async()=>({}),onAuthStateChange(){}},from(table){const q={select(){return this;},order(){return this;},range(){return this;},eq(){return this;},ilike(){return this;},then(resolve){resolve({data:table==='properties'?[{id:'one',title_id:'<img src=x onerror=alert(1)>',title_en:'Villa',slug:'test',publication_status:'draft',property_type:'villa',purpose:'rent'}]:[],count:table==='properties'?1:0});}};return q;}};
 globalThis.__aupTestClient=fake;globalThis.fetch=async()=>new Response(JSON.stringify({images:[]}),{status:200,headers:{'Content-Type':'application/json'}});
 const schema=pathToFileURL(resolve('admin/schema.js')).href;
 const code=source.replace("import {createClient} from '@supabase/supabase-js';",'const createClient=()=>globalThis.__aupTestClient;').replace("from './schema.js'",'from '+JSON.stringify(schema));
 await import('data:text/javascript;base64,'+Buffer.from(code+'\n// test '+iteration++).toString('base64'));return window.document;
}
test('signed-out visitors only see login and accessible fields',async()=>{const doc=await openPanel(null,false);assert.ok(doc.querySelector('#login'));assert.equal(doc.querySelector('input[name=password]').getAttribute('autocomplete'),'current-password');assert.equal(doc.querySelectorAll('[data-section]').length,0);});
test('editor sees content, not private admin menus; hostile title remains text',async()=>{const doc=await openPanel('editor');assert.equal(doc.querySelector('[data-section=inquiries]'),null);assert.equal(doc.querySelector('[data-section=site_settings]'),null);assert.equal(doc.querySelector('.cards img'),null);assert.match(doc.querySelector('.card h3').textContent,/<img/);await doc.querySelector('[data-edit]').onclick();assert.ok(doc.querySelector('#editor'));assert.ok(doc.querySelector('[name=publication_status]'));assert.ok(doc.querySelector('#upload'));});
test('admin sees private menus, empty inquiries and guest moment controls',async()=>{const doc=await openPanel('admin');assert.ok(doc.querySelector('[data-section=inquiries]'));assert.ok(doc.querySelector('[data-section=site_settings]'));await doc.querySelector('[data-section=inquiries]').onclick();assert.match(doc.querySelector('.empty').textContent,/Pertanyaan pelanggan/);assert.equal(doc.querySelector('#add'),null);await doc.querySelector('[data-section=guest_moments]').onclick();assert.ok(doc.querySelector('#add'));});
