import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {pathToFileURL} from 'node:url';import {resolve} from 'node:path';import {parseHTML} from 'linkedom';
const source=await readFile(new URL('../app.js',import.meta.url),'utf8');let iteration=0;
async function openPanel(role,authenticated=true,options={}){
 const {window}=parseHTML('<html><body><main id="app"></main><div id="notice"></div></body></html>');Object.assign(globalThis,{window,document:window.document,sessionStorage:{},confirm:()=>true,FormData:class{constructor(form){this.items=new Map(Array.from(form.querySelectorAll('[name]')).filter(el=>el.type!=='checkbox'||el.checked).map(el=>[el.name,el.type==='checkbox'?'on':el.value]));}get(name){return this.items.get(name)??null;}}});const selectedValues=new WeakMap();Object.defineProperty(window.HTMLSelectElement.prototype,'value',{configurable:true,get(){return selectedValues.get(this)??Array.from(this.options).find(o=>o.hasAttribute('selected'))?.value??this.options[0]?.value??'';},set(value){selectedValues.set(this,value);}});
 window.HTMLElement.prototype.scrollIntoView=()=>{};
 const user={id:'test',email:'admin@example.invalid',app_metadata:{aup_role:role}};
 const fake={auth:{getSession:async()=>({data:{session:authenticated?{access_token:'fake'}:null}}),getUser:async()=>({data:{user}}),signOut:async()=>({}),onAuthStateChange(){}},from(table){const q={update(payload){options.updates?.push({table,payload});this.payload=payload;return this;},single:async()=>({data:{},error:options.updateError}),select(){return this;},order(){return this;},range(){return this;},eq(){return this;},ilike(){return this;},then(resolve){resolve({data:options.records?.[table]??(table==='properties'?[{id:'one',title_id:'<img src=x onerror=alert(1)>',title_en:'Villa',slug:'test',publication_status:'draft',property_type:'villa',purpose:'rent'}]:[]),count:table==='properties'?1:0});}};return q;}};
 globalThis.__aupTestClient=fake;globalThis.fetch=async()=>new Response(JSON.stringify({images:[]}),{status:200,headers:{'Content-Type':'application/json'}});
 const schema=pathToFileURL(resolve('admin/schema.js')).href;
 const code=source.replace("import {createClient} from '@supabase/supabase-js';",'const createClient=()=>globalThis.__aupTestClient;').replace("from './schema.js'",'from '+JSON.stringify(schema)).replace("from '../supabase/functions/public-catalog/settings.js'",'from '+JSON.stringify(pathToFileURL(resolve('supabase/functions/public-catalog/settings.js')).href));
 await import('data:text/javascript;base64,'+Buffer.from(code+'\n// test '+iteration++).toString('base64'));return window.document;
}
test('signed-out visitors only see login and accessible fields',async()=>{const doc=await openPanel(null,false);assert.ok(doc.querySelector('#login'));assert.equal(doc.querySelector('input[name=password]').getAttribute('autocomplete'),'current-password');assert.equal(doc.querySelectorAll('[data-section]').length,0);});
test('editor sees content, not private admin menus; hostile title remains text',async()=>{const doc=await openPanel('editor');assert.equal(doc.querySelector('[data-section=inquiries]'),null);assert.equal(doc.querySelector('#section-picker option[value=inquiries]'),null);assert.equal(doc.querySelector('[data-section=site_settings]'),null);assert.equal(doc.querySelector('.cards img'),null);assert.match(doc.querySelector('.card h3').textContent,/<img/);await doc.querySelector('[data-edit]').onclick();assert.ok(doc.querySelector('#editor'));assert.ok(doc.querySelector('[name=publication_status]'));assert.ok(doc.querySelector('#upload'));});
test('admin sees private menus, empty inquiries and guest moment controls',async()=>{const doc=await openPanel('admin');assert.ok(doc.querySelector('[data-section=inquiries]'));assert.ok(doc.querySelector('#section-picker option[value=inquiries]'));assert.ok(doc.querySelector('[data-section=site_settings]'));await doc.querySelector('[data-section=inquiries]').onclick();assert.match(doc.querySelector('.empty').textContent,/Tiket dari formulir/);assert.equal(doc.querySelector('#add'),null);await doc.querySelector('[data-section=guest_moments]').onclick();assert.ok(doc.querySelector('#add'));});

test('mobile dropdown changes the selected management section',async()=>{const doc=await openPanel('admin');await doc.querySelector('#section-picker').onchange({target:{value:'motorbikes'}});assert.equal(doc.querySelector('h1').textContent,'Rental motor');assert.equal(doc.querySelector('[data-section=motorbikes]').getAttribute('aria-current'),'page');});

test('ticket form shows request context and saves only status/notes, preserving customer data',async()=>{
 const updates=[];const doc=await openPanel('admin',true,{updates,records:{inquiries:[{id:'ticket',ticket_no:'AUP-100099',inquiry_type:'property',properties:{title_id:'Villa <b>aman</b>'},name:'Customer',email:'test@example.invalid',message:'Customer message',language:'id',status:'new',created_at:'2026-10-09T10:00:00Z'}]}});
 await doc.querySelector('[data-section=inquiries]').onclick();assert.match(doc.querySelector('.card').textContent,/Properti/);await doc.querySelector('[data-edit]').onclick();assert.match(doc.querySelector('.ticket-context').textContent,/Villa <b>aman<\/b>/);assert.equal(doc.querySelector('.ticket-context b'),null);
 doc.querySelector('[name=status]').value='in_progress';doc.querySelector('[name=internal_notes]').value='Called customer';doc.querySelector('[name=name]').value='Tampered';await doc.querySelector('#editor').onsubmit({preventDefault(){}});assert.deepEqual(updates,[{table:'inquiries',payload:{status:'in_progress',internal_notes:'Called customer'}}]);
});
test('guest publish requires consent before writing, then persists captions/location/status',async()=>{
 const updates=[];const doc=await openPanel('admin',true,{updates,records:{guest_moments:[{id:'guest',caption_id:'Momen',caption_en:'Moment',location_label:'Ubud',publication_status:'draft',consent_confirmed:false}]}});
 await doc.querySelector('[data-section=guest_moments]').onclick();assert.equal(doc.querySelector('#add').textContent,'+ Tambah foto');await doc.querySelector('[data-edit]').onclick();doc.querySelector('[name=publication_status]').value='published';await doc.querySelector('#editor').onsubmit({preventDefault(){}});assert.equal(updates.length,0);assert.match(doc.querySelector('#save-error').textContent,/izin publikasi/);assert.equal(doc.querySelector('[name=caption_id]').value,'Momen');doc.querySelector('[name=consent_confirmed]').checked=true;await doc.querySelector('#editor').onsubmit({preventDefault(){}});assert.equal(updates[0].payload.consent_confirmed,true);assert.equal(updates[0].payload.publication_status,'published');assert.equal(updates[0].payload.location_label,'Ubud');
});
test('failed admin ticket save keeps status and notes on screen without a success notice',async()=>{
 const updates=[];const doc=await openPanel('admin',true,{updates,updateError:{message:'Network unavailable'},records:{inquiries:[{id:'ticket',ticket_no:'AUP-100102',inquiry_type:'service',services:{title_id:'Perizinan'},status:'new',created_at:'2026-10-09T10:00:00Z'}]}});await doc.querySelector('[data-section=inquiries]').onclick();await doc.querySelector('[data-edit]').onclick();doc.querySelector('[name=status]').value='contacted';doc.querySelector('[name=internal_notes]').value='Follow up tomorrow';await doc.querySelector('#editor').onsubmit({preventDefault(){}});assert.equal(doc.querySelector('[name=status]').value,'contacted');assert.equal(doc.querySelector('[name=internal_notes]').value,'Follow up tomorrow');assert.match(doc.querySelector('#save-error').textContent,/Koneksi terputus/);assert.equal(doc.querySelector('#save').disabled,false);assert.doesNotMatch(doc.querySelector('#notice').textContent,/Perubahan tersimpan/);
});
