import test from 'node:test';import assert from 'node:assert/strict';
import {escapeHTML,payloadFrom,sections} from '../schema.js';
import {imageType,staffRole,validUUID} from '../../supabase/functions/admin-media/validation.js';
test('untrusted content is escaped before rendering',()=>assert.equal(escapeHTML('<img src=x onerror="alert(1)">'), '&lt;img src=x onerror=&quot;alert(1)&quot;&gt;'));
test('metadata from customer cannot grant staff access',()=>{assert.equal(staffRole({id:'u',user_metadata:{aup_role:'owner'}}),false);assert.equal(staffRole({id:'u',app_metadata:{aup_role:'admin'}}),true);assert.equal(staffRole({app_metadata:{aup_role:'admin'}}),false);});
test('inquiry editor only changes status and internal notes',()=>{const data=new FormData();data.set('name','attacker');data.set('email','attacker@example.com');data.set('status','closed');data.set('internal_notes','Done');assert.deepEqual(payloadFrom(sections.inquiries.fields,data),{status:'closed',internal_notes:'Done'});});
test('reject negative prices and fractional bedrooms',()=>{for(const [key,value] of [['price','-1'],['bedrooms','1.5']]){const field=sections.properties.fields.find(f=>f.key===key);const form=new FormData();form.set(key,value);assert.throws(()=>payloadFrom([field],form));}});
test('blank numeric input is null, checkbox false, facilities trimmed',()=>{const form=new FormData();form.set('price','');form.set('facilities','Pool\n\n Wifi ');assert.deepEqual(payloadFrom(sections.properties.fields.filter(f=>['price','is_featured','facilities'].includes(f.key)),form),{price:null,facilities:['Pool','Wifi'],is_featured:false});});
test('uploaded extensions cannot spoof image type',()=>{assert.equal(imageType(new TextEncoder().encode('<svg onload=alert(1)>')),null);assert.deepEqual(imageType(new Uint8Array([255,216,255])),['image/jpeg','jpg']);assert.deepEqual(imageType(new Uint8Array([137,80,78,71,13,10,26,10])),['image/png','png']);assert.equal(validUUID('../secrets'),false);});
