import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import {parseHTML} from 'linkedom';import {handle} from '../supabase/functions/public-catalog/index.js';
const id='74f847f1-f32d-450c-a64a-7af7d7368301',env={url:'https://db.example',anon:'anonymous',key:'server-secret'};
const json=data=>new Response(JSON.stringify(data));
async function mock(fn,run){const old=globalThis.fetch;globalThis.fetch=fn;try{await run();}finally{globalThis.fetch=old;}}
test('guest catalog reads only published consented rows anonymously and never selects private paths',async()=>{
 await mock(async(url,init)=>{const p=new URL(url).searchParams;assert.equal(init.headers.Authorization,'Bearer anonymous');assert.match(url,/guest_moments/);assert.equal(p.get('publication_status'),'eq.published');assert.equal(p.get('consent_confirmed'),'eq.true');assert.equal(p.get('order'),'sort_order.asc,id.asc');assert.equal(p.get('limit'),'20');assert.equal(p.get('offset'),'20');assert.doesNotMatch(p.get('select'),/storage_path|consent_confirmed/);return json([{id,caption_id:'Asli'}]);},async()=>{const response=await handle(new Request('https://example.com?kind=guest&page=1',{headers:{Authorization:'Bearer owner-token'}}),env);assert.deepEqual(await response.json(),{moments:[{id,caption_id:'Asli'}],hasMore:false});assert.equal(response.headers.get('cache-control'),'no-store');assert.equal((await handle(new Request('https://example.com?kind=guest&page=-1'),env)).status,400);});
});
test('guest image signs only approved database path for five minutes; drafts and arbitrary paths are rejected',async()=>{
 let signs=0;await mock(async(url,init)=>{if(url.includes('/guest_moments?')){assert.equal(init.headers.Authorization,'Bearer anonymous');assert.equal(new URL(url).searchParams.get('consent_confirmed'),'eq.true');return json([{storage_path:'guest_moments/'+id+'/'+id+'.jpg'}]);}signs++;assert.equal(init.headers.Authorization,'Bearer server-secret');assert.equal(JSON.parse(init.body).expiresIn,300);return json({signedURL:'/object/sign/aup-media/guest_moments/photo.jpg?token=test'});},async()=>{const response=await handle(new Request('https://example.com?kind=guest&image='+id+'&path=properties/forged.jpg'),env);assert.equal(response.status,302);assert.equal(response.headers.get('cache-control'),'no-store');assert.equal(signs,1);});
 for(const rows of [[],[{storage_path:'properties/'+id+'/'+id+'.jpg'}],[{storage_path:'guest_moments/../private.jpg'}]])await mock(async url=>{assert.match(url,/guest_moments/);return json(rows);},async()=>{assert.equal((await handle(new Request('https://example.com?kind=guest&image='+id),env)).status,404);});
});
async function page({dedicated=false,rows=[],fail=false,more=false}={}){
 const {window,document}=parseHTML(`<html><body class="${dedicated?'guest-moments-page':''}"><button id="languageToggle"></button><button id="guestLanguage"></button><section id="about"></section>${dedicated?'<h1 data-gm-copy="pageTitle"></h1><div id="guestMomentsGrid"></div>':''}</body></html>`);window.HTMLElement.prototype.focus=function(){document.__focused=this;};let lang='id',calls=[];
 vm.runInNewContext(fs.readFileSync('guest-moments.js','utf8'),{window,document,localStorage:{getItem:()=>lang,setItem:(key,v)=>lang=v},AbortSignal,setTimeout,Date,fetch:async url=>{calls.push(url);if(fail)throw Error('offline');const page=new URL(url).searchParams.get('page');return json({moments:page==='1'?[{id:'74f847f1-f32d-450c-a64a-7af7d7368302',caption_id:'Kedua'}]:rows,hasMore:page==='0'&&more});}});await new Promise(r=>setTimeout(r,15));return {window,document,calls};
}
test('guest photos and captions are real, escaped and language-aware; dialog closes and returns focus',async()=>{
 const {window,document}=await page({dedicated:true,rows:[{id,caption_id:'<img src=x onerror=alert(1)>',caption_en:'Real moment',location_label:'<b>Ubud</b>'}]});assert.equal(document.querySelectorAll('#guestMomentsGrid img').length,1);const button=document.querySelector('[data-gm-id]');assert.match(button.textContent,/<img/);assert.equal(button.querySelector('b'),null);assert.match(button.querySelector('img').src,/kind=guest&image=/);button.click();assert.equal(document.querySelector('.gm-lightbox').hidden,false);assert.equal(document.querySelector('.gm-lightbox').getAttribute('aria-modal'),'true');const key=new window.Event('keydown');key.key='Escape';document.querySelector('.gm-lightbox').dispatchEvent(key);assert.equal(document.querySelector('.gm-lightbox').hidden,true);assert.equal(document.__focused,button);document.querySelector('#guestLanguage').click();assert.equal(document.querySelector('[data-gm-id] small').textContent,'Real moment');
});
test('empty/error galleries never use sample imagery and support retry',async()=>{
 for(const dedicated of [false,true])for(const fail of [false,true]){const {document}=await page({dedicated,fail});assert.equal(document.querySelectorAll('[data-gm-id]').length,0);assert.match(document.querySelector('.gm-state').textContent,fail?/belum bisa dimuat/:/segera hadir/);assert.equal(!!document.querySelector('[data-gm-retry]'),fail);assert.equal(document.querySelectorAll('img').length,0);}
});
test('homepage limits preview to six and dedicated gallery paginates without losing existing cards',async()=>{
 const rows=Array.from({length:8},(_,i)=>({id:'74f847f1-f32d-450c-a64a-7af7d73683'+String(i+10),caption_id:'Moment '+i}));let p=await page({rows});assert.equal(p.document.querySelectorAll('[data-gm-id]').length,6);p=await page({dedicated:true,rows,more:true});p.document.querySelector('[data-gm-more]').click();await new Promise(r=>setTimeout(r,15));assert.equal(p.document.querySelectorAll('[data-gm-id]').length,9);assert.match(p.calls[1],/page=1/);assert.equal(p.document.querySelector('[data-gm-more]'),null);
});
