import {createClient} from '@supabase/supabase-js';
import {sections,settingFields,escapeHTML as esc,payloadFrom} from './schema.js';
const url='https://tvcmwkzwemrwwewphfgh.supabase.co';
const key='sb_publishable_ctqO41Koy2Q_TdHjYRkCkQ_5wcL-id2';
const db=createClient(url,key,{auth:{storage:sessionStorage,storageKey:'aup-admin-session',detectSessionInUrl:false}});
const app=document.querySelector('#app');let user,section='properties',page=0,rows=[],total=0,locations=[],dirty=false,requestVersion=0;const pageSize=20;
const statusLabels={draft:'Draft',published:'Terbit',archived:'Arsip',new:'Baru',contacted:'Dihubungi',in_progress:'Ditangani',closed:'Selesai',spam:'Spam'};
function notice(message,error=false){const el=document.querySelector('#notice');el.textContent=message;el.className='show'+(error?' error':'');clearTimeout(notice.timer);notice.timer=setTimeout(()=>el.className='',6000);}
function humanError(error){if(error.code==='23505')return 'Alamat halaman sudah dipakai. Gunakan slug yang berbeda.';if(error.code==='23514')return 'Periksa isian dan izin publikasi foto/ulasan.';if(error.code==='42501')return 'Akses ditolak. Masuk ulang atau hubungi pengelola.';if(/Invalid login credentials/i.test(error.message))return 'Email atau password belum cocok.';if(/fetch|network/i.test(error.message))return 'Koneksi terputus. Isian tetap disimpan di layar; coba lagi.';return error.message||'Terjadi kesalahan. Coba lagi.';}
async function checked(result){if(result.error)throw result.error;return result.data;}
const isAdmin=()=>['owner','admin'].includes(user?.app_metadata?.aup_role);
async function authorized(){const fresh=await checked(await db.auth.getUser());if(!['owner','admin','editor'].includes(fresh.user?.app_metadata?.aup_role))throw Error('Akun ini belum memiliki akses pengelola.');user=fresh.user;return user;}
function login(){dirty=false;user=null;document.body.classList.remove('editing');app.removeAttribute('aria-busy');app.innerHTML=`<section class="login"><p class="eyebrow">RUANG PENGELOLAAN</p><h1>Selamat datang.</h1><p class="muted">Kelola properti dan konten Agung Ubud dari satu tempat.</p><form id="login"><div class="field"><label for="email">Email</label><input id="email" name="email" type="email" autocomplete="username" required></div><div class="field"><label for="password">Password</label><div class="password-wrap"><input id="password" name="password" type="password" autocomplete="current-password" required><button type="button" class="secondary" id="show-password" aria-label="Tampilkan password" aria-pressed="false">Lihat</button></div></div><p id="login-error" class="error" role="alert"></p><button type="submit">Masuk ke panel</button></form><p class="muted">Gunakan akun pengelola yang sudah terdaftar. Hubungi pengelola jika perlu bantuan akses.</p></section>`;
document.querySelector('#show-password').onclick=e=>{const p=document.querySelector('#password');const visible=p.type==='password';p.type=visible?'text':'password';e.target.textContent=visible?'Sembunyi':'Lihat';e.target.setAttribute('aria-pressed',String(visible));e.target.setAttribute('aria-label',visible?'Sembunyikan password':'Tampilkan password');};
document.querySelector('#login').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('[type=submit]');button.disabled=true;button.textContent='Memeriksa akun…';try{const form=new FormData(e.target);await checked(await db.auth.signInWithPassword({email:form.get('email'),password:form.get('password')}));await authorized();e.target.reset();await shell();}catch(error){await db.auth.signOut({scope:'local'});document.querySelector('#login-error').textContent=humanError(error);}finally{button.disabled=false;button.textContent='Masuk ke panel';}};
}
function canLeave(){return !dirty||confirm('Ada perubahan yang belum disimpan. Tinggalkan form ini?');}
async function shell(){dirty=false;document.body.classList.remove('editing');app.innerHTML=`<div class="toolbar"><p class="muted">${esc(user.email)} · ${esc(user.app_metadata.aup_role)}</p><button id="logout" class="outline">Keluar</button></div><nav class="nav" aria-label="Menu pengelolaan">${Object.entries(sections).filter(([,s])=>!s.admin||isAdmin()).map(([id,s])=>`<button data-section="${id}" aria-current="${id===section?'page':'false'}">${s.label}</button>`).join('')}</nav><section id="content"></section>`;
document.querySelector('#logout').onclick=async()=>{if(!canLeave())return;requestVersion++;await db.auth.signOut({scope:'local'});login();};
app.querySelectorAll('[data-section]').forEach(button=>button.onclick=async()=>{if(!canLeave())return;dirty=false;section=button.dataset.section;page=0;app.querySelectorAll('[data-section]').forEach(b=>b.setAttribute('aria-current',b===button?'page':'false'));await list();});await list();}
function primary(row){return row.title_id||row.name||row.display_name||row.caption_id||row.key||'Tanpa judul';}
async function list(search='',status=''){const version=++requestVersion;document.body.classList.remove('editing');const content=document.querySelector('#content');content.innerHTML='<p role="status">Memuat data…</p>';try{await authorized();if(sections[section].admin&&!isAdmin())throw Error('Hanya owner/admin yang dapat membuka bagian ini.');const current=section;
let query=db.from(current).select('*',{count:'exact'}).order(current==='site_settings'?'key':'created_at',{ascending:current==='site_settings'}).range(page*pageSize,(page+1)*pageSize-1);
if(search){const field=current==='properties'||current==='services'?'title_id':current==='testimonials'?'display_name':current==='guest_moments'?'caption_id':current==='site_settings'?'key':'name';query=query.ilike(field,'%'+search.replace(/[\\%_]/g,'\\$&')+'%');}
if(status)query=query.eq(current==='inquiries'?'status':'publication_status',status);
const result=await query;if(result.error)throw result.error;if(version!==requestVersion)return;rows=result.data;total=result.count;renderList(search,status);}catch(error){if(version!==requestVersion)return;content.innerHTML=`<section class="empty"><h2>Data belum bisa dimuat</h2><p class="error">${esc(humanError(error))}</p><button id="retry">Coba lagi</button></section>`;document.querySelector('#retry').onclick=()=>list(search,status);}}
function renderList(search,status){const s=sections[section];const canAdd=section!=='inquiries';const published=s.fields.some(f=>f.key==='publication_status');const statusOptions=section==='inquiries'?['new','contacted','in_progress','closed','spam']:['draft','published','archived'];
document.querySelector('#content').innerHTML=`<div class="page-heading"><div><p class="eyebrow">PENGELOLAAN</p><h1>${s.label}</h1><p class="muted">${total} data${search||status?' sesuai pencarian':''}</p></div>${canAdd?'<button id="add">+ Tambah</button>':''}</div><form id="filters" class="filters"><input name="search" aria-label="Cari ${s.label}" placeholder="Cari nama atau judul…" value="${esc(search)}">${published||section==='inquiries'?`<select name="status" aria-label="Filter status"><option value="">Semua status</option>${statusOptions.map(x=>`<option value="${x}" ${status===x?'selected':''}>${statusLabels[x]}</option>`).join('')}</select>`:''}<button class="secondary">Cari</button></form><div class="cards">${rows.length?rows.map((row,i)=>`<article class="card"><span class="badge ${esc(row.publication_status||row.status||'')}">${esc(statusLabels[row.publication_status||row.status]||(row.is_active===false?'Nonaktif':'Aktif'))}</span><h3>${esc(primary(row))}</h3><p class="muted">${esc(section==='inquiries'?row.message?.slice(0,140):row.property_type||row.slug||row.location_label||'')}</p>${row.price!=null?`<p>${esc(row.currency)} ${Number(row.price).toLocaleString('id-ID')}</p>`:''}${section==='inquiries'?`<small>${new Date(row.created_at).toLocaleDateString('id-ID')}</small>`:''}<div class="actions"><button class="outline" data-edit="${i}">${section==='inquiries'?'Buka pesan':'Edit'}</button></div></article>`).join(''):`<section class="empty"><h2>${search||status?'Belum ada hasil':'Belum ada data'}</h2><p class="muted">${search||status?'Coba kata kunci atau status lain.':section==='inquiries'?'Pertanyaan pelanggan akan muncul di sini saat formulir website sudah terhubung.':'Mulai tambahkan data pertama. Konten baru disimpan sebagai draft.'}</p></section>`}</div><div class="pagination"><button id="prev" class="secondary" ${page===0?'disabled':''}>← Sebelumnya</button><small>Halaman ${page+1}</small><button id="next" class="secondary" ${(page+1)*pageSize>=total?'disabled':''}>Berikutnya →</button></div><p class="help">Properti & kos berstatus Terbit otomatis tampil di katalog website. Draft dan arsip hanya terlihat oleh pengelola. Halaman rental motor dan konten lain masih dalam tahap integrasi.</p>`;
document.querySelector('#filters').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);page=0;list(String(f.get('search')||''),String(f.get('status')||''));};
const again=()=>list(search,status);document.querySelector('#prev').onclick=()=>{page--;again();};document.querySelector('#next').onclick=()=>{page++;again();};if(canAdd)document.querySelector('#add').onclick=()=>edit({});app.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>edit(rows[Number(b.dataset.edit)]));}
function fieldHTML(field,row){let value=row[field.key]??field.default??'';const id='field-'+field.key;let input;const common=`id="${id}" name="${field.key}" ${field.required?'required':''} ${field.readonly?'readonly':''}`;
if(field.type==='checkbox')return `<div class="field"><label for="${id}"><input ${common} type="checkbox" ${value?'checked':''}>${esc(field.label)}</label></div>`;
if(field.type==='select'||field.type==='location'){const opts=field.type==='location'?[['','Belum dipilih'],...locations.map(x=>[x.id,x.name])]:field.options;input=`<select ${common}>${opts.map(opt=>{const [v,label]=Array.isArray(opt)?opt:[opt,opt];return `<option value="${esc(v)}" ${String(value)===String(v)?'selected':''}>${esc(label)}</option>`;}).join('')}</select>`;}
else if(field.type==='textarea'||field.type==='array')input=`<textarea ${common} maxlength="${field.key==='message'?5000:12000}">${esc(Array.isArray(value)?value.join('\n'):value)}</textarea>`;
else input=`<input ${common} type="${field.type}" value="${esc(value)}" ${field.max?'max'+(field.type==='number'?'':'length')+'="'+field.max+'"':''} ${field.type==='number'?`min="${field.min??0}" step="${field.step??'0.01'}" inputmode="decimal"`:''} ${field.pattern?`pattern="${field.pattern}"`:''}>`;
return `<div class="field ${['textarea','array'].includes(field.type)?'wide':''}"><label for="${id}">${esc(field.label)}${field.required?' *':''}</label>${input}${field.key==='slug'?'<small>Huruf kecil, angka, dan tanda hubung. Contoh: vila-ubud-hijau.</small>':''}</div>`;}
async function edit(row){const current=section,version=++requestVersion;try{await authorized();if(current==='properties')locations=await checked(await db.from('locations').select('id,name').order('name'));if(version!==requestVersion)return;let fields=sections[current].fields;
if(current==='site_settings'){fields=[{key:'key',label:'Bagian website',type:'select',options:Object.keys(settingFields),readonly:!!row.key}];if(row.key)fields=[{key:'key',label:'Bagian website',type:'text',readonly:true},...settingFields[row.key].map(key=>({key,label:key.replace(/_/g,' '),type:key.startsWith('description')?'textarea':'text'}))];}
const formRow=current==='site_settings'?{...row.value,key:row.key}:row;document.body.classList.add('editing');document.querySelector('#content').innerHTML=`<section class="editor"><p class="eyebrow">${sections[current].label}</p><h2>${row.id||row.key?'Edit data':'Tambah data'}</h2><form id="editor"><div class="form-grid">${fields.map(f=>fieldHTML(f,formRow)).join('')}</div>${current==='site_settings'?'<p class="help">Isian ini bersifat publik. Jangan masukkan password, kunci API, atau catatan pelanggan.</p>':''}${sections[current].media?`<section id="photos"><h3>Foto</h3><p class="muted">${row.id?'Foto disimpan privat.':'Simpan data terlebih dahulu untuk menambahkan foto.'}</p><div id="media-list" class="media"></div>${row.id&&current!=='guest_moments'?'<label class="upload-label">Tambah foto<small>JPG, PNG, atau WebP · maksimal 8 MB per foto</small><input id="upload" type="file" accept="image/jpeg,image/png,image/webp" multiple></label>':''}</section>`:''}<p id="save-error" class="error" role="alert"></p><div class="save-bar"><button type="button" class="secondary" id="cancel">Kembali</button><button type="submit" id="save">Simpan${row.id||row.key?'':' draft'}</button></div></form></section>`;
dirty=false;const form=document.querySelector('#editor');form.oninput=()=>dirty=true;document.querySelector('#cancel').onclick=()=>{if(canLeave()){dirty=false;list();}};
if(current==='site_settings'&&!row.key)document.querySelector('[name=key]').onchange=e=>{const selected=e.target.value;form.querySelector('.form-grid').innerHTML=fieldHTML(fields[0],{key:selected})+settingFields[selected].map(k=>fieldHTML({key:k,label:k.replace(/_/g,' '),type:'text'},{})).join('');};
if(current==='site_settings'&&!row.key){const select=document.querySelector('[name=key]');select.dispatchEvent(new Event('change'));}
form.onsubmit=async e=>{e.preventDefault();const save=document.querySelector('#save');save.disabled=true;save.textContent='Menyimpan…';document.querySelector('#save-error').textContent='';try{await authorized();let payload;
if(current==='site_settings'){const data=new FormData(form),key=row.key||data.get('key');payload={key,value:{...(row.value||{})}};for(const f of settingFields[key])payload.value[f]=String(data.get(f)||'').trim();await checked(await (row.key?db.from(current).update({value:payload.value}).eq('key',row.key):db.from(current).insert(payload)).select().single());}
else{payload=payloadFrom(fields,new FormData(form));if(!row.id&&current==='guest_moments'){throw Error('Tambahkan foto momen terlebih dahulu lewat tombol upload di daftar momen.');}if(row.id){await checked(await db.from(current).update(payload).eq('id',row.id).select().single());}else{const saved=await checked(await db.from(current).insert(payload).select().single());dirty=false;notice('Data tersimpan. Kamu bisa menambahkan foto.');await edit(saved);return;}}
dirty=false;notice('Perubahan tersimpan.');await list();}catch(error){document.querySelector('#save-error').textContent=humanError(error);document.querySelector('#save-error').scrollIntoView({block:'nearest'});}finally{save.disabled=false;save.textContent='Simpan';}};
if(row.id&&sections[current].media){await mediaList(current,row.id);if(current!=='guest_moments')document.querySelector('#upload').onchange=async e=>{const files=Array.from(e.target.files);e.target.disabled=true;try{for(const file of files){if(file.size>8*1024*1024)throw Error('Foto terlalu besar. Maksimal 8 MB per foto.');const data=new FormData();data.set('table',current);data.set('id',row.id);data.set('file',file);await mediaRequest(data);}notice('Foto berhasil ditambahkan.');await mediaList(current,row.id);}catch(error){notice(humanError(error),true);}finally{e.target.disabled=false;e.target.value='';}};}
}catch(error){notice(humanError(error),true);}}
async function mediaRequest(body){const session=await checked(await db.auth.getSession());const response=await fetch(url+'/functions/v1/admin-media',{method:'POST',headers:{apikey:key,Authorization:'Bearer '+session.session?.access_token,...(body instanceof FormData?{}:{'Content-Type':'application/json'})},body:body instanceof FormData?body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw Error(data.error||'Foto belum berhasil diproses.');return data;}
async function mediaList(table,id){const el=document.querySelector('#media-list');try{const data=await mediaRequest({action:'list',table,id});el.innerHTML=data.images.map(image=>`<figure><img src="${esc(image.url)}" alt="Foto konten" loading="lazy"><figcaption>${image.is_cover?'Foto utama':'Foto galeri'}</figcaption>${table!=='guest_moments'?`<button type="button" class="secondary" data-remove="${image.id}">Hapus foto</button>`:''}</figure>`).join('');el.querySelectorAll('[data-remove]').forEach(button=>button.onclick=async()=>{if(!confirm('Hapus foto ini dari konten?'))return;button.disabled=true;try{await mediaRequest({action:'remove',table,id,image_id:button.dataset.remove});await mediaList(table,id);notice('Foto dihapus.');}catch(error){notice(humanError(error),true);button.disabled=false;}});}catch(error){el.innerHTML=`<p class="error">${esc(humanError(error))}</p>`;}}
// New guest moments start with a real uploaded photo, never a guessed object path.
const originalRenderList=renderList;renderList=function(search,status){originalRenderList(search,status);if(section==='guest_moments'){document.querySelector('#add').onclick=()=>{const input=document.createElement('input');input.type='file';input.accept='image/jpeg,image/png,image/webp';input.onchange=async()=>{if(!input.files[0])return;const data=new FormData();data.set('table','guest_moments');data.set('file',input.files[0]);try{notice('Mengunggah foto…');const result=await mediaRequest(data);await edit(result.record);}catch(error){notice(humanError(error),true);}};input.click();};}};
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
db.auth.onAuthStateChange(event=>{if(event==='SIGNED_OUT'&&user){requestVersion++;login();}});
try{const session=await checked(await db.auth.getSession());if(session.session){await authorized();await shell();}else login();}catch{await db.auth.signOut({scope:'local'});login();}finally{app.removeAttribute('aria-busy');}
