const f=(key,label,type='text',extra={})=>({key,label,type,...extra});
const publication=f('publication_status','Status tayang','select',{options:[['draft','Draft'],['published','Terbit'],['archived','Arsip']]});
const titles=[f('title_id','Judul · Indonesia','text',{required:true,max:200}),f('title_en','Judul · English','text',{required:true,max:200})];
const descriptions=[f('description_id','Deskripsi · Indonesia','textarea'),f('description_en','Deskripsi · English','textarea')];
const slug=f('slug','Alamat halaman (slug)','text',{required:true,pattern:'[a-z0-9]+(-[a-z0-9]+)*'});
const currency=f('currency','Mata uang','select',{options:['IDR','USD']});
const sort=f('sort_order','Urutan tampil','number',{default:0,min:0,step:1});
export const sections={
 dashboard:{label:'Ringkasan',fields:[]},
 properties:{label:'Properti & kos',fields:[...titles,slug,f('property_type','Jenis','select',{options:[['villa','Vila'],['house','Rumah'],['land','Tanah'],['rental','Sewa'],['commercial','Komersial'],['kost','Kos']]}),f('purpose','Tujuan','select',{options:[['rent','Disewakan'],['sale','Dijual']]}),f('location_id','Lokasi','location'),f('address_public','Alamat publik'),f('price','Harga','number'),currency,f('price_period','Periode harga','select',{options:[['total','Total'],['night','Malam'],['day','Hari'],['month','Bulan'],['year','Tahun']]}),f('tenure','Kepemilikan','select',{options:[['','Belum ditentukan'],'freehold','leasehold']}),f('bedrooms','Kamar tidur','number',{step:1}),f('bathrooms','Kamar mandi','number',{step:1}),f('land_area_m2','Luas tanah (m²)','number'),f('building_area_m2','Luas bangunan (m²)','number'),...descriptions,f('facilities','Fasilitas · satu per baris','array'),publication,f('availability','Ketersediaan','select',{options:[['available','Tersedia'],['reserved','Dipesan'],['sold','Terjual'],['rented','Disewa'],['unavailable','Tidak tersedia']]}),f('is_featured','Tampilkan sebagai unggulan','checkbox')],media:'property_images',parent:'property_id'},
 motorbikes:{label:'Rental motor',fields:[f('name','Nama motor','text',{required:true,max:150}),slug,f('daily_price','Harga per hari','number'),f('monthly_price','Harga per bulan','number'),currency,f('engine_cc','Kapasitas mesin (cc)','number',{min:1,step:1}),...descriptions,f('included_items','Termasuk · satu per baris','array'),publication,f('availability','Ketersediaan','select',{options:[['available','Tersedia'],['unavailable','Tidak tersedia']]}),sort],media:'motorbike_images',parent:'motorbike_id'},
 locations:{label:'Lokasi',fields:[f('name','Nama lokasi','text',{required:true,max:120}),slug,...descriptions,sort,f('is_active','Lokasi aktif','checkbox',{default:true})]},
 services:{label:'Layanan',fields:[...titles,slug,...descriptions,publication,sort]},
 testimonials:{label:'Ulasan',fields:[f('display_name','Nama yang ditampilkan','text',{required:true,max:150}),f('quote_id','Ulasan · Indonesia','textarea',{required:true}),f('quote_en','Ulasan · English','textarea',{required:true}),f('rating','Rating 1–5','number',{required:true,min:1,max:5,step:1,default:5}),...descriptions,f('consent_confirmed','Sudah mendapat izin untuk menampilkan ulasan','checkbox'),publication,sort]},
 guest_moments:{label:'Momen tamu',fields:[f('caption_id','Keterangan · Indonesia','textarea'),f('caption_en','Keterangan · English','textarea'),f('location_label','Nama lokasi'),f('consent_confirmed','Sudah mendapat izin publikasi foto tamu','checkbox'),publication,sort],media:'guest_moments'},
 inquiries:{label:'Tiket pelanggan',admin:true,fields:[f('ticket_no','Nomor tiket','text',{readonly:true}),f('name','Nama','text',{readonly:true}),f('email','Email','text',{readonly:true}),f('phone','Telepon','text',{readonly:true}),f('message','Pesan','textarea',{readonly:true}),f('status','Status tindak lanjut','select',{options:[['new','Baru'],['contacted','Sudah dihubungi'],['in_progress','Diproses'],['closed','Selesai'],['spam','Spam']]}),f('internal_notes','Catatan internal','textarea')]},
 site_settings:{label:'Pengaturan website',admin:true,fields:[]}
};
export const settingFields={contact:['email','phone','whatsapp','address'],social_links:['instagram','facebook','youtube','tiktok'],brand:['name','tagline'],homepage:['title_id','title_en','description_id','description_en']};
export function escapeHTML(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
export function payloadFrom(fields,form){const out={};for(const field of fields){if(field.readonly)continue;const v=form.get(field.key);if(field.type==='checkbox')out[field.key]=v==='on';else if(field.type==='number'){out[field.key]=v===''?null:Number(v);if(out[field.key]!==null&&(!Number.isFinite(out[field.key])||out[field.key]<(field.min??0)||(field.max!==undefined&&out[field.key]>field.max)||(field.step===1&&!Number.isInteger(out[field.key]))))throw Error('Periksa '+field.label);}else if(field.type==='array')out[field.key]=String(v??'').split('\n').map(x=>x.trim()).filter(Boolean);else out[field.key]=field.key==='location_id'||field.key==='tenure'?(v||null):String(v??'').trim();}return out;}
